version: '3'

services:
  web:
    container_name: coronapageant
    image: glenster75/coronapageant
    environment:
      - TZ=America/Los_Angeles
    ports:
      - '80:80'
    restart: unless-stopped
